# -*- coding: utf-8 -*-
"""analisis_carrier_V9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ug3aKUWhoWdl60zSKkka0kpgUiarRH9
"""

!pip install statsforecast openpyxl

# ==========================================================
# 1️⃣ LIBRERÍAS
# ==========================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsforecast.models import CrostonClassic, CrostonSBA
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.api import Holt
import openpyxl
from openpyxl.styles import PatternFill
from scipy.stats import zscore
import warnings

warnings.filterwarnings('ignore')

# ==========================================================
# 2️⃣ CARGA DE DATOS
# ==========================================================
print("Cargando datos...")
# Histórico pivoteado (embarques)
hist = pd.read_excel("data_carrier_embarcado2025.xlsx")
hist.fillna(0, inplace=True)

# Follow-Up actual
columnas_fu = [
    'Sem', 'Cliente', 'City', 'Numero de parte', 'Id', 'Rev', 'EAU',
    'Req', 'Emb', 'Saldo', 'Venta', 'Rel', 'Fecha', 'Real', 'Class',
    'Familia', 'Peso KG', 'PO Line', 'PO Fecha', 'Comentario / NPI NUME',
    'Release Number', 'Estatus Ing', 'Planta Embarque', 'Moneda',
    'PO Encabezado', 'Pintura', 'Attention', 'STATUS',
    'Pzas Embar Apodaca - Santa', "Planeado"
]

followup = pd.read_excel("FollowUp_viejo.xlsx", skiprows=1)
followup.columns = columnas_fu[:len(followup.columns)]
followup['Saldo'] = pd.to_numeric(followup['Saldo'], errors='coerce').fillna(0)
followup['Req'] = pd.to_numeric(followup['Req'], errors='coerce').fillna(0) # --- CORRECCIÓN --- Asegurar que Req sea numérico
followup['Fecha'] = pd.to_datetime(followup['Fecha'], errors='coerce')

followup_nuevo = pd.read_excel("Follow Up 2.0100248_nuevo.xlsx", skiprows=1)
followup_nuevo.columns = columnas_fu[:len(followup_nuevo.columns)]
followup_nuevo['Saldo'] = pd.to_numeric(followup_nuevo['Saldo'], errors='coerce').fillna(0)
followup_nuevo['Req'] = pd.to_numeric(followup_nuevo['Req'], errors='coerce').fillna(0) # --- CORRECCIÓN --- Asegurar que Req sea numérico
followup_nuevo['Fecha'] = pd.to_datetime(followup_nuevo['Fecha'], errors='coerce')

print("Datos cargados.")

# ==========================================================
# 3️⃣ CLASIFICACIÓN DE PATRONES DE DEMANDA (Syntetos–Boylan)
# ==========================================================
print("Clasificando demanda (Syntetos-Boylan)...")
id_col = 'Numero de parte'
data_cols = hist.columns.drop(id_col)
data = hist[data_cols]

def calc_metrics(row):
    series = row[data_cols]
    series_nonzero = series[series > 0]
    if len(series_nonzero) == 0:
        mean = 0
        cv = 0
    else:
        mean = series_nonzero.mean()
        cv = series_nonzero.std() / (mean + 1e-6)
    p = (series > 0).sum() / len(series)
    return pd.Series({'mean': mean, 'cv': cv, 'p0': p})

hist[['mean','cv','p0']] = hist.apply(calc_metrics, axis=1)

def classify_syntetos_boylan(row):
    cv2 = row['cv']**2
    p0 = row['p0']
    if cv2 <= 0.49 and p0 > 0.5:
        return 'Smooth'
    elif cv2 > 0.49 and p0 > 0.5:
        return 'Erratic'
    elif cv2 <= 0.49 and p0 <= 0.5:
        return 'Intermittent'
    else:
        return 'Lumpy'

hist['Tipo_SB'] = hist.apply(classify_syntetos_boylan, axis=1)
model_map = {'Smooth':'SES','Erratic':'Holt','Intermittent':'CrostonClassic','Lumpy':'CrostonSBA'}
hist['Modelo_Pronostico'] = hist['Tipo_SB'].map(model_map)

# ==========================================================
# 4️⃣ PRONÓSTICOS (Basados en S-B)
# ==========================================================
print("Generando pronósticos...")
def forecast_series(series, tipo, horizon=3):
    series = pd.Series(series).astype(float).fillna(0)
    if (series==0).all():
        return np.zeros(horizon)
    try:
        if tipo=='Smooth':
            fit = ExponentialSmoothing(series, trend=None, seasonal=None).fit()
            fcast = fit.forecast(horizon)
        elif tipo=='Erratic':
            fit = Holt(series).fit()
            fcast = fit.forecast(horizon)
        elif tipo=='Intermittent':
            fcast = CrostonClassic().forecast(y=series.to_numpy(), h=horizon)
            fcast = np.array(fcast['mean']).flatten()
        elif tipo=='Lumpy':
            fcast = CrostonSBA().forecast(y=series.to_numpy(), h=horizon)
            fcast = np.array(fcast['mean']).flatten()
        else:
            fcast = np.full(horizon, np.mean(series))
        if len(fcast) < horizon:
            fcast = np.pad(fcast, (0, horizon - len(fcast)), 'constant', constant_values=0)
        return fcast
    except:
        return np.full(horizon, np.mean(series))

forecast_records = []
horizon = 3

for idx, row in hist.iterrows():
    serie = data.loc[idx]
    tipo = row['Tipo_SB']
    fcast = forecast_series(serie, tipo, horizon)
    rec = {'Numero de parte': row[id_col], 'Tipo_SB': tipo, 'Modelo_Pronostico': row['Modelo_Pronostico']}
    for i in range(horizon):
        rec[f'Semana_+{i+1}'] = fcast[i]
    forecast_records.append(rec)

df_forecast = pd.DataFrame(forecast_records)

# ==========================================================
# 5️⃣ REFACTORIZACIÓN: FUNCIÓN DE CÁLCULO DE PLAN Y RIESGO
# ==========================================================
print("Refactorizando lógica de scoring...")

def generar_plan_con_score(df_followup_source, df_hist, df_forecast_base, df_variacion, es_baseline=False):
    """
    Toma un dataframe de followup (viejo o nuevo) y calcula el plan
    completo con su score de riesgo proactivo.
    """
    id_col = 'Numero de parte'

    # 1. Consolidar el followup (por si hay duplicados)
    df_followup_merge = (
        df_followup_source.groupby(id_col, as_index=False)
        .agg({
            'Saldo': 'sum',
            'Fecha': 'min',
            "Class": "first",
            "Req": "sum"
        })
    )

    # 2. Merge con la base de pronósticos (S-B)
    df_plan = df_forecast_base.merge(df_followup_merge, on=id_col, how='left')

    # 3. Añadir 'cv' del histórico
    df_plan = df_plan.merge(
        df_hist[['Numero de parte', 'cv']],
        on='Numero de parte',
        how='left'
    )

    # 4. Identificar y consolidar partes nuevas (basado en el followup de entrada)
    nuevas_partes = set(df_followup_source[id_col]) - set(df_hist[id_col])
    df_nuevas = df_followup_source[df_followup_source[id_col].isin(nuevas_partes)].copy()

    dfnuevas_merge = (
        df_nuevas.groupby(id_col, as_index=False)
        .agg({
            'Saldo': 'sum',
            'Fecha': 'min',
            'Req': 'sum',
            'Class': 'first'
        })
    )
    dfnuevas_merge['Tipo_SB'] = 'Nueva'

    # 5. Unir partes con historia y nuevas
    df_plan_final = pd.concat([df_plan, dfnuevas_merge], ignore_index=True)
    df_plan_final['Tipo_demanda_o_nueva'] = df_plan_final['Tipo_SB'].fillna('Nueva')

    # Imputar CV
    cv_median = df_hist['cv'].median()
    df_plan_final['cv'] = df_plan_final['cv'].fillna(cv_median)

    # 6. Añadir variación de forecast (Deltas)
    if es_baseline:
        # Si es el plan 'Viernes', no hay 'nerviosismo'. Todo es 0.
        df_plan_final['delta_forecast_abs'] = 0
        df_plan_final['delta_forecast_pct'] = 0
    else:
        # Si es el plan 'Martes', usamos la variación calculada
        df_plan_final = df_plan_final.merge(
            df_variacion[['Numero de parte', 'delta_forecast_abs', 'delta_forecast_pct']],
            on='Numero de parte',
            how='left'
        )
        # Imputar deltas para partes que no estaban en df_variacion
        df_plan_final['delta_forecast_abs'] = df_plan_final['delta_forecast_abs'].fillna(0)
        df_plan_final['delta_forecast_pct'] = df_plan_final['delta_forecast_pct'].fillna(0)

    # 7. CÁLCULO DE RIESGO (Lógica de la Sección 7 original)
    hoy = pd.Timestamp.today()
    df_plan_final['Días_para_entrega'] = (df_plan_final['Fecha'] - hoy).dt.days
    df_plan_final['Saldo'] = df_plan_final['Saldo'].clip(lower=0).fillna(0)
    df_plan_final['Req'] = df_plan_final['Req'].clip(lower=0).fillna(0)

    # Normalización
    with np.errstate(invalid='ignore'): # Suprimir warnings de división por cero si Z-score es 0
        df_plan_final['norm_saldo'] = (zscore(df_plan_final['Saldo']).clip(-2, 2) + 2) / 4
        df_plan_final['norm_demanda'] = (zscore(df_plan_final['Req']).clip(-2, 2) + 2) / 4
        df_plan_final['norm_variabilidad'] = (zscore(df_plan_final['cv']).clip(-2, 2) + 2) / 4
        df_plan_final['norm_delta_forecast'] = (zscore(df_plan_final['delta_forecast_pct']).clip(-2, 2) + 2) / 4

    for c in ['norm_saldo', 'norm_demanda', 'norm_variabilidad', 'norm_delta_forecast']:
        df_plan_final[c] = df_plan_final[c].clip(0, 1).fillna(0)

    # Ponderaciones
    peso_tipo = {
        'Smooth':       {'saldo': 0.3, 'demanda': 0.3, 'variabilidad': 0.1, 'delta': 0.3},
        'Erratic':      {'saldo': 0.4, 'demanda': 0.2, 'variabilidad': 0.2, 'delta': 0.2},
        'Intermittent': {'saldo': 0.5, 'demanda': 0.2, 'variabilidad': 0.1, 'delta': 0.2},
        'Lumpy':        {'saldo': 0.6, 'demanda': 0.2, 'variabilidad': 0.1, 'delta': 0.1},
        'Nueva':        {'saldo': 0.4, 'demanda': 0.4, 'variabilidad': 0.0, 'delta': 0.2}
    }

    def calc_risk_proactivo(row):
        w = peso_tipo.get(row.get('Tipo_demanda_o_nueva', 'Smooth'))
        risk = (
            w['saldo'] * row['norm_saldo'] +
            w['demanda'] * row['norm_demanda'] +
            w['variabilidad'] * row['norm_variabilidad'] +
            w['delta'] * row['norm_delta_forecast']
        )
        return risk

    df_plan_final['score_prioridad_proactivo'] = df_plan_final.apply(calc_risk_proactivo, axis=1)

    df_plan_final['Nivel_prioridad'] = pd.cut(
        df_plan_final['score_prioridad_proactivo'],
        bins=[-0.01, 0.33, 0.66, 1.0],
        labels=['Baja', 'Media', 'Alta']
    )

    # Calcular Backorder
    df_plan_final['Es_backorder'] = df_plan_final['Fecha'] < hoy
    df_backorder = df_plan_final[df_plan_final['Es_backorder']].groupby('Numero de parte')['Saldo'].sum().reset_index()
    df_backorder = df_backorder.rename(columns={'Saldo':'Backorder'})

    df_plan_final = df_plan_final.merge(df_backorder, on='Numero de parte', how='left')
    df_plan_final['Backorder'] = df_plan_final['Backorder'].fillna(0)

    return df_plan_final

# ==========================================================
# 6️⃣ CÁLCULO VARIACIÓN FORECAST (Lógica de Sección 6 original)
# ==========================================================
print("Calculando variación de forecast...")
prev_agg = (
    followup.groupby('Numero de parte', as_index=False)['Req']
    .sum()
    .rename(columns={'Req': 'Req_ant'})
)
new_agg = (
    followup_nuevo.groupby('Numero de parte', as_index=False)['Req']
    .sum()
    .rename(columns={'Req': 'Req_nuevo'})
)
df_variacion = pd.merge(new_agg, prev_agg, on='Numero de parte', how='left')
df_variacion['delta_forecast_abs'] = df_variacion['Req_nuevo'] - df_variacion['Req_ant']
df_variacion['delta_forecast_pct'] = df_variacion['delta_forecast_abs'] / (df_variacion['Req_ant'] + 1e-6)
df_variacion['delta_forecast_abs'] = df_variacion['delta_forecast_abs'].fillna(df_variacion['Req_nuevo'])
df_variacion['delta_forecast_pct'] = df_variacion['delta_forecast_pct'].fillna(1.0)

# ==========================================================
# 7️⃣ EJECUCIÓN: CALCULAR AMBOS PLANES
# ==========================================================
print("Calculando Score del Martes (Nuevo)...")
# (df_forecast es el resultado de la Sección 4 del script original)
df_plan_martes = generar_plan_con_score(
    df_followup_source=followup_nuevo,
    df_hist=hist,
    df_forecast_base=df_forecast,
    df_variacion=df_variacion,
    es_baseline=False
).rename(columns={'score_prioridad_proactivo': 'score_martes', 'Nivel_prioridad': 'Nivel_martes'})

print("Calculando Score del Viernes (Baseline)...")
df_plan_viernes = generar_plan_con_score(
    df_followup_source=followup, # <-- Usamos el followup viejo
    df_hist=hist,
    df_forecast_base=df_forecast,
    df_variacion=df_variacion,    # Se pasará, pero 'es_baseline=True' lo neutraliza
    es_baseline=True             # <-- CLAVE: Esto pone los deltas en 0
).rename(columns={'score_prioridad_proactivo': 'score_viernes', 'Nivel_prioridad': 'Nivel_viernes'})

# ==========================================================
# 🔹 4️⃣ Filtrar horizonte operativo
# ==========================================================
# --- CORRECCIÓN ---
# ¡¡SE ELIMINA EL FILTRO DE 7 DÍAS DE AQUÍ!!
# El df_plan_final se mantiene íntegro. El filtro se aplica en el reporte final (Sección 8).
# --- FIN DE CORRECCIÓN ---

# ==========================================================
# 8️⃣ REPORTE DE EXCEPCIONES (Lógica de Integración)
# ==========================================================
print("Generando Reporte de Excepciones...")

# 1. Columnas clave para comparar
cols_viernes = ['Numero de parte', 'score_viernes', 'Nivel_viernes', 'Saldo', 'Req']
cols_martes = ['Numero de parte', 'score_martes', 'Nivel_martes', 'Saldo', 'Req', 'delta_forecast_pct', 'Tipo_demanda_o_nueva']

# 2. Hacer el merge (outer join)
df_comparativo = pd.merge(
    df_plan_martes[cols_martes].rename(columns={'Saldo': 'Saldo_mar', 'Req': 'Req_mar'}),
    df_plan_viernes[cols_viernes].rename(columns={'Saldo': 'Saldo_vie', 'Req': 'Req_vie'}),
    on='Numero de parte',
    how='outer'
)

# --- INICIA CORRECCIÓN DE TYPEERROR ---

# Rellenar NaNs en columnas numéricas con 0
numeric_cols = ['score_martes', 'Saldo_mar', 'Req_mar',
                'score_viernes', 'Saldo_vie', 'Req_vie',
                'delta_forecast_pct']
for col in numeric_cols:
    if col in df_comparativo.columns:
        df_comparativo[col] = df_comparativo[col].fillna(0)

# Rellenar NaNs en columnas categóricas con un string 'N/A'
cat_cols = ['Nivel_martes', 'Nivel_viernes', 'Tipo_demanda_o_nueva']
for col in cat_cols:
    if col in df_comparativo.columns:
        if pd.api.types.is_categorical_dtype(df_comparativo[col]):
             if 'N/A' not in df_comparativo[col].cat.categories:
                df_comparativo[col] = df_comparativo[col].cat.add_categories(['N/A'])
        df_comparativo[col] = df_comparativo[col].fillna('N/A')

# --- FIN DE CORRECCIÓN ---

df_comparativo['cambio_score'] = df_comparativo['score_martes'] - df_comparativo['score_viernes']

# 3. Definir los filtros de excepción (AJUSTADOS A NIVELES DE PRIORIDAD)
# --- INICIA AJUSTE DE UMBRALES ---
UMBRAL_ALTO = 0.66 # Límite para 'Alta' prioridad
UMBRAL_BAJO = 0.33 # Límite para 'Baja' prioridad

# PULL-IN: No eran 'Alta' (<= 0.66) y ahora SÍ son 'Alta' (> 0.66)
df_pull_ins = df_comparativo[
    (df_comparativo['score_martes'] > UMBRAL_ALTO) &
    (df_comparativo['score_viernes'] <= UMBRAL_ALTO)
].sort_values(by='score_martes', ascending=False)

# PUSH-OUT: Eran 'Alta' (> 0.66) y ahora son 'Baja' (<= 0.33)
df_push_outs = df_comparativo[
    (df_comparativo['score_martes'] <= UMBRAL_BAJO) &
    (df_comparativo['score_viernes'] > UMBRAL_ALTO)
].sort_values(by='cambio_score', ascending=True)
# --- FIN DE AJUSTE DE UMBRALES ---

# 4. Desplegar (Exportar el reporte accionable)
if not df_pull_ins.empty or not df_push_outs.empty:
    with pd.ExcelWriter("Reporte_Excepciones_MARTES.xlsx") as writer:
        df_pull_ins.to_excel(writer, sheet_name="1_Adelantar_PULL_IN", index=False)
        df_push_outs.to_excel(writer, sheet_name="2_Detener_PUSH_OUT", index=False)
    print("ÉXITO: 'Reporte_Excepciones_MARTES.xlsx' generado.")
else:
    print("INFO: No se encontraron excepciones significativas esta semana.")

# ==========================================================
# 9️⃣ GENERACIÓN DE REPORTE DE CARGA SEMANAL (Lógica V1)
# ==========================================================
# (Esta sección recrea tu reporte 'Resumen_Carga_Semanal' original,
# pero usando el plan del Martes)
print("Generando Resumen de Carga Semanal (7 días)...")

hoy = pd.Timestamp.today()

# 1. Filtrar el followup_nuevo al horizonte de 7 días (esto mantiene la granularidad de línea)
followup_horizonte = followup_nuevo.loc[
    (followup_nuevo['Fecha'] <= hoy + pd.Timedelta(days=7)) &
    (followup_nuevo['Fecha'].notna()) # Asegurarse de no tener fechas nulas
].copy()

if followup_horizonte.empty:
    print("INFO: No se encontraron items en el horizonte de 7 días. No se generará 'Resumen_Carga_Semanal_7_DIAS.xlsx'.")
else:
    # 2. Pivotar la demanda semanal (agregada por Numero de parte)
    followup_horizonte['Semana_relativa'] = ((followup_horizonte['Fecha'] - hoy).dt.days // 7 + 1).clip(1,3)
    df_followup_pivot = followup_horizonte.pivot_table(
        index='Numero de parte',
        columns='Semana_relativa',
        values='Saldo',
        aggfunc='sum',
        fill_value=0
    ).reset_index().rename(columns={1:'Demanda_+1', 2:'Demanda_+2', 3:'Demanda_+3'})

    # 3. Columnas a mantener del reporte de línea
    # (Añade 'PO Line' o 'Release Number' si las tienes y quieres verlas)
    cols_linea = ['Numero de parte', 'Saldo', 'Fecha', 'Class', 'Req', 'PO Line', 'Release Number']
    # Seleccionar solo las columnas que existen en el dataframe
    cols_a_usar = [col for col in cols_linea if col in followup_horizonte.columns]

    # 4. Columnas a traer del plan maestro (ya tienen el backorder)
    #    (df_plan_martes fue creado en la Sección 7)
    cols_plan = ['Numero de parte', 'Tipo_demanda_o_nueva', 'score_martes', 'Nivel_martes', 'Backorder']

    # 5. Merge "Muchos-a-Uno": Múltiples líneas de pedido con 1 score por parte
    df_resumen_carga = followup_horizonte[cols_a_usar].merge(
        df_plan_martes[cols_plan],
        on='Numero de parte',
        how='left'
    )

    # 6. Merge con la demanda pivotada (semanal)
    df_resumen_carga = df_resumen_carga.merge(
        df_followup_pivot,
        on='Numero de parte',
        how='left'
    )

    # Rellenar NaNs en demanda semanal (para partes sin demanda en esas semanas)
    for col in ['Demanda_+1', 'Demanda_+2', 'Demanda_+3']:
        if col in df_resumen_carga.columns:
            df_resumen_carga[col] = df_resumen_carga[col].fillna(0)

    # 7. Ordenar por score de prioridad y luego fecha
    df_resumen_carga = df_resumen_carga.sort_values(
        by=["score_martes", "Fecha"],
        ascending=[False, True]
    ).reset_index(drop=True)

    # 8. Exportar
    ruta_excel_resumen = "Resumen_Carga_Semanal_7_DIAS.xlsx"
    df_resumen_carga.to_excel(ruta_excel_resumen, index=False)

    print(f"ÉXITO: Reporte de carga semanal generado: {ruta_excel_resumen}")

# ==========================================================
# 10️⃣ EXPORTACIÓN DE REPORTE MAESTRO
# ==========================================================
print("Generando reporte maestro completo...")
ruta_excel_plan = "PlanProduccion_Prioridad_COMPLETO_MARTES.xlsx"
df_plan_martes.sort_values(by="score_martes", ascending=False).to_excel(ruta_excel_plan, index=False)
print(f"ÉXITO: Reporte principal del Martes generado: {ruta_excel_plan}")

print("\n--- Proceso de Priorización completado ---")